serverAddr = "nas.computercau.top"
serverPort = 7910
auth.token = "12345"


[[proxies]]
name = "lhl-qc"
type = "tcp"
localIP = "127.0.0.1"
localPort = 18481
remotePort = 12480

[[proxies]]
name = "lhl-qc-67-22"
type = "tcp"
localIP = "127.0.0.1"
localPort = 18422
remotePort = 12482